### ISSUE TITLE
Multiple FileNotFoundError

### ISSUE THREAD

**Issue by csngh** [dapascual/DirectedBeamSearch#2]
Hi Team DBS,

So I'm trying to run the code as it is mentioned in the instructions provided by you guys and I'm facing too many errors while getting it to run. I'll try my best to list everything down.

Firstly it throws:
```
Traceback (most recent call last):
  File "main_DBS.py", line 37, in <module>
    generate_look_ups(word_vectors)         ### WATCH OUT WITH CONVERT TABLE GLOVE
NameError: name 'word_vectors' is not defined
```

Then after commenting that block down, as I didn't see any further usage of ```word_vectors``` anywhere in the file, it threw:
```
Save path:  results/50_keywordsets_eval/deterministic_result_w_20_nBeams_5_nConcSent_5_nGenSent_18_nWordsPerSent_5_temperature_1.0
Keywords:  ['enemy', 'speed', 'meet', 'colony', 'mouth']
N keywords:  5
Traceback (most recent call last):
  File "main_DBS.py", line 511, in <module>
    key2article=False
  File "main_DBS.py", line 255, in conditional_language_generation
    text_file = open(save_path + '.txt', 'a+', encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: 'results/50_keywordsets_eval/deterministic_result_w_20_nBeams_5_nConcSent_5_nGenSent_18_nWordsPerSent_5_temperature_1.0.txt'
```

And after creating the file manually (for the sake of moving one step forward) it threw:
```
Save path:  results/50_keywordsets_eval/deterministic_result_w_20_nBeams_5_nConcSent_5_nGenSent_18_nWordsPerSent_5_temperature_1.0
Keywords:  ['enemy', 'speed', 'meet', 'colony', 'mouth']
N keywords:  5
Traceback (most recent call last):
  File "main_DBS.py", line 511, in <module>
    key2article=False
  File "main_DBS.py", line 265, in conditional_language_generation
    os.path.abspath(__file__))) + '/data/converter_table_glove.npy')  
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/content/DirectedBeamSearch/data/converter_table_glove.npy'
```

Alternatively, If I do not comment out ```generate_look_ups(word_vectors)``` and load ```"glove-wiki-gigaword-300"``` it throws this:
```
Before
Traceback (most recent call last):
  File "main_DBS.py", line 37, in <module>
    generate_look_ups(word_vectors)         ### WATCH OUT WITH CONVERT TABLE GLOVE
  File "/content/DirectedBeamSearch/utility_gpt.py", line 65, in generate_look_ups
    converter_table()
  File "/content/DirectedBeamSearch/utility_gpt.py", line 127, in converter_table
    enc = encoder.get_encoder(model_name, models_dir)
NameError: name 'encoder' is not defined
```
 
Thanks and great work :)

**Comment by dapascual** [comment]
Hi csngh, thanks for opening this issue. I have updated the code and now it should work without needing to change anything. Please download the new version of the code and try:
python encode_keywords.py
and then:
python main_DBS.py

It should work, if it doesn't please let me know!

**Comment by csngh** [comment]
Yes it works now 👍 
Thanks a lot for fixing the issue.
